spring:
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS:localhost}:${DB_PORT:5432}/${DB_DATABASE:gonion_identity}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
  servlet:
    context-path: /v1/gonion/identity
  port: ${BASE_PORT:8080}
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/api-docs
value:
  aws-access-key-id: ${AWS_ACCESS_KEY_ID:}
  aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  front-end-base-url: ${FRONT_END_BASE_URL:}
